// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2020, STMicroelectronics - All Rights Reserved
 * Author(s): Raphaël GALLAIS-POU <raphael.gallais-pou@st.com> for STMicroelectronics.
 */

#include<stdio.h>
#include<stdlib.h>

#define HEX_BASE	16


typedef enum
{
  HAL_LVDS_MAP_R_0  = 0x00U,
  HAL_LVDS_MAP_R_1  = 0x01U,
  HAL_LVDS_MAP_R_2  = 0x02U,
  HAL_LVDS_MAP_R_3  = 0x03U,
  HAL_LVDS_MAP_R_4  = 0x04U,
  HAL_LVDS_MAP_R_5  = 0x05U,
  HAL_LVDS_MAP_R_6  = 0x06U,
  HAL_LVDS_MAP_R_7  = 0x07U,
  HAL_LVDS_MAP_G_0  = 0x08U,
  HAL_LVDS_MAP_G_1  = 0x09U,
  HAL_LVDS_MAP_G_2  = 0x0AU,
  HAL_LVDS_MAP_G_3  = 0x0BU,
  HAL_LVDS_MAP_G_4  = 0x0CU,
  HAL_LVDS_MAP_G_5  = 0x0DU,
  HAL_LVDS_MAP_G_6  = 0x0EU,
  HAL_LVDS_MAP_G_7  = 0x0FU,
  HAL_LVDS_MAP_B_0  = 0x10U,
  HAL_LVDS_MAP_B_1  = 0x11U,
  HAL_LVDS_MAP_B_2  = 0x12U,
  HAL_LVDS_MAP_B_3  = 0x13U,
  HAL_LVDS_MAP_B_4  = 0x14U,
  HAL_LVDS_MAP_B_5  = 0x15U,
  HAL_LVDS_MAP_B_6  = 0x16U,
  HAL_LVDS_MAP_B_7  = 0x17U,
  HAL_LVDS_MAP_H_S  = 0x18U,
  HAL_LVDS_MAP_V_S  = 0x19U,
  HAL_LVDS_MAP_D_E  = 0x1AU,
  HAL_LVDS_MAP_C_E  = 0x1BU,
  HAL_LVDS_MAP_C_I  = 0x1CU,
  HAL_LVDS_MAP_TOG  = 0x1DU,
  HAL_LVDS_MAP_ONE  = 0x1EU,
  HAL_LVDS_MAP_ZERO	= 0x1FU,
} HAL_LVDS_MapTypeDef;


// Expected JEIDA-RGB888 data to be sent in LSB format
//          bit6 ............................bit0
// CHAN0   {ONE, ONE, ZERO, ZERO, ZERO, ONE, ONE}
// CHAN1   {G2,  R7,  R6,   R5,   R4,   R3,  R2}
// CHAN2   {B3,  B2,  G7,   G6,   G5,   G4,  G3}
// CHAN3   {DE,  VS,  HS,   B7,   B6,   B5,  B4}
// CHAN4   {CE,  B1,  B0,   G1,   G0,   R1,  R0}

const HAL_LVDS_MapTypeDef HAL_LVDS_Map_JEIDA_RGB888[5][7] = {
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_G_2, HAL_LVDS_MAP_R_7, HAL_LVDS_MAP_R_6,  HAL_LVDS_MAP_R_5,  HAL_LVDS_MAP_R_4,  HAL_LVDS_MAP_R_3, HAL_LVDS_MAP_R_2},
    {HAL_LVDS_MAP_B_3, HAL_LVDS_MAP_B_2, HAL_LVDS_MAP_G_7,  HAL_LVDS_MAP_G_6,  HAL_LVDS_MAP_G_5,  HAL_LVDS_MAP_G_4, HAL_LVDS_MAP_G_3},
    {HAL_LVDS_MAP_D_E, HAL_LVDS_MAP_V_S, HAL_LVDS_MAP_H_S,  HAL_LVDS_MAP_B_7,  HAL_LVDS_MAP_B_6,  HAL_LVDS_MAP_B_5, HAL_LVDS_MAP_B_4},
    {HAL_LVDS_MAP_C_E, HAL_LVDS_MAP_B_1, HAL_LVDS_MAP_B_0,  HAL_LVDS_MAP_G_1,  HAL_LVDS_MAP_G_0,  HAL_LVDS_MAP_R_1, HAL_LVDS_MAP_R_0}};

// Expected VESA-RGB888 data to be sent in LSB format
//          bit6 ............................bit0
// CHAN0   {ONE, ONE, ZERO, ZERO, ZERO, ONE, ONE}
// CHAN1   {G0,  R5,  R4,   R3,   R2,   R1,  R0}
// CHAN2   {B1,  B0,  G5,   G4,   G3,   G2,  G1}
// CHAN3   {DE,  VS,  HS,   B5,   B4,   B3,  B2}
// CHAN4   {CE,  B7,  B6,   G7,   G6,   R7,  R6}

const HAL_LVDS_MapTypeDef HAL_LVDS_Map_VESA_RGB888[5][7] = {
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_G_0, HAL_LVDS_MAP_R_5, HAL_LVDS_MAP_R_4,  HAL_LVDS_MAP_R_3,  HAL_LVDS_MAP_R_2,  HAL_LVDS_MAP_R_1, HAL_LVDS_MAP_R_0},
    {HAL_LVDS_MAP_B_1, HAL_LVDS_MAP_B_0, HAL_LVDS_MAP_G_5,  HAL_LVDS_MAP_G_4,  HAL_LVDS_MAP_G_3,  HAL_LVDS_MAP_G_2, HAL_LVDS_MAP_G_1},
    {HAL_LVDS_MAP_D_E, HAL_LVDS_MAP_V_S, HAL_LVDS_MAP_H_S,  HAL_LVDS_MAP_B_5,  HAL_LVDS_MAP_B_4,  HAL_LVDS_MAP_B_3, HAL_LVDS_MAP_B_2},
    {HAL_LVDS_MAP_C_E, HAL_LVDS_MAP_B_7, HAL_LVDS_MAP_B_6,  HAL_LVDS_MAP_G_7,  HAL_LVDS_MAP_G_6,  HAL_LVDS_MAP_R_7, HAL_LVDS_MAP_R_6}};

// Expected JEIDA/VESA-RGB666 data to be sent in LSB format
//          bit6 ............................bit0
// CHAN0   {ONE, ONE, ZERO, ZERO, ZERO, ONE, ONE}
// CHAN1   {G2,  R7,  R6,   R5,   R4,   R3,  R2}
// CHAN2   {B3,  B2,  G7,   G6,   G5,   G4,  G3}
// CHAN3   {DE,  VS,  HS,   B7,   B6,   B5,  B4}
// CHAN4   {00,  00,  00,   00,   00,   00,  00}

const HAL_LVDS_MapTypeDef HAL_LVDS_Map_RGB666[5][7] = {
    {HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_G_2,  HAL_LVDS_MAP_R_7,  HAL_LVDS_MAP_R_6,   HAL_LVDS_MAP_R_5,   HAL_LVDS_MAP_R_4,   HAL_LVDS_MAP_R_3,  HAL_LVDS_MAP_R_2},
    {HAL_LVDS_MAP_B_3,  HAL_LVDS_MAP_B_2,  HAL_LVDS_MAP_G_7,   HAL_LVDS_MAP_G_6,   HAL_LVDS_MAP_G_5,   HAL_LVDS_MAP_G_4,  HAL_LVDS_MAP_G_3},
    {HAL_LVDS_MAP_D_E,  HAL_LVDS_MAP_V_S,  HAL_LVDS_MAP_H_S,   HAL_LVDS_MAP_B_7,   HAL_LVDS_MAP_B_6,   HAL_LVDS_MAP_B_5,  HAL_LVDS_MAP_B_4},
    {HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ZERO,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO}};

// Pattern data for testing purpose
const HAL_LVDS_MapTypeDef HAL_LVDS_Map_DSKW[5][7] = {
#if defined(DSKW_DEFAULT)
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_D_E, HAL_LVDS_MAP_V_S,  HAL_LVDS_MAP_H_S,  HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_C_E, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO}};
#elif defined(DSKW_OTHER)
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_D_E, HAL_LVDS_MAP_V_S, HAL_LVDS_MAP_H_S, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_C_E, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE}};
#elif defined(DSKW_TOGGLE)
    {HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ONE, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG},
    {HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG},
    {HAL_LVDS_MAP_D_E, HAL_LVDS_MAP_V_S, HAL_LVDS_MAP_H_S, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG},
    {HAL_LVDS_MAP_B_0, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG, HAL_LVDS_MAP_TOG}};
#elif defined(DSKW_ZERO)
    {HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ONE,  HAL_LVDS_MAP_ONE},
    {HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_D_E,  HAL_LVDS_MAP_V_S,  HAL_LVDS_MAP_H_S,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO},
    {HAL_LVDS_MAP_C_E,  HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO, HAL_LVDS_MAP_ZERO}};
#endif

int LVDS_Decode(HAL_LVDS_MapTypeDef** map, int reg)
{
        if (reg > 0xFFFFFFFF || reg < 0x0)
                return 1;
}

int main(int argc, char **argv)
{
	if (argc != 2)
		return 1;

	int reg = (int)strtol(argv[1], NULL, HEX_BASE);
	printf("%d\n", reg);
	return 0;
}
